name: Backend CI & Discord Notifications

on:
  pull_request:
    branches: [ main ]
    types: [ opened, closed ]  # PR이 열릴 때와 닫힐 때(머지 포함)
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: 👋 Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1

      - name: ☕️ Set up JDK 21
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: 🔐 Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: backend/project2/
        shell: bash

      - name: 🛠 Build with Gradle with test profile
        run: sudo ./gradlew build -Pprofile=test
        working-directory: backend/project2/
        shell: bash

  discordNotification:
    needs: backend-ci
    runs-on: ubuntu-latest
    steps:
      # PR 성공 알림
      - name: Discord Notification on Success (PR)
        if: success() && github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: discord-actions/message@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            ✅ **Backend CI Passed!**
            **Event:** Pull Request
            **Repo:** ${{ github.repository }}
            **PR Title:** ${{ github.event.pull_request.title }}
            **Author:** ${{ github.event.pull_request.user.login }}
            **PR Link:** ${{ github.event.pull_request.html_url }}

      # PR 실패 알림
      - name: Discord Notification on Failure (PR)
        if: failure() && github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: discord-actions/message@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            ❌ **Backend CI Failed!**
            **Event:** Pull Request
            **Repo:** ${{ github.repository }}
            **PR Title:** ${{ github.event.pull_request.title }}
            **Author:** ${{ github.event.pull_request.user.login }}
            **PR Link:** ${{ github.event.pull_request.html_url }}

      # Push 성공 알림
      - name: Discord Notification on Success (Push)
        if: success() && github.event_name == 'push'
        uses: discord-actions/message@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            ✅ **Backend CI Passed!**
            **Event:** Push
            **Repo:** ${{ github.repository }}
            **Branch:** ${{ github.ref }}
            **Commit:** [${{ github.event.head_commit.message }}](${{ github.event.head_commit.url }})
            **Pusher:** ${{ github.event.pusher.name }}

      # Push 실패 알림
      - name: Discord Notification on Failure (Push)
        if: failure() && github.event_name == 'push'
        uses: discord-actions/message@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            ❌ **Backend CI Failed!**
            **Event:** Push
            **Repo:** ${{ github.repository }}
            **Branch:** ${{ github.ref }}
            **Commit:** [${{ github.event.head_commit.message }}](${{ github.event.head_commit.url }})
            **Pusher:** ${{ github.event.pusher.name }}

      # PR Merge 알림
      - name: Discord Notification on PR Merge
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: discord-actions/message@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            🎉 **Pull Request Merged!**
            **Repo:** ${{ github.repository }}
            **PR Title:** ${{ github.event.pull_request.title }}
            **Merged by:** ${{ github.event.pull_request.merged_by.login }}
            **PR Link:** ${{ github.event.pull_request.html_url }}
